//put your loop point data here

sound_add_included("guyrock.mp3",1,1)
sound_add_included("Sidewinder___Timeless___01_Analyzer.ogg",1,1)
sound_add_included("Sidewinder___Timeless___02_Keisha.ogg",1,1)
sound_add_included("Sidewinder___Timeless___03_Imagine_When.ogg",1,1)
sound_add_included("Sidewinder___Timeless___04_Beyond_Dreams.ogg",1,1)
sound_add_included("Sidewinder___Timeless___06_Beyond_the_Game.ogg",1,1)
sound_add_included("Sidewinder___Timeless___08_What_Life.ogg",1,1)
sound_add_included("Sidewinder___Timeless___10_Tribelands.ogg",1,1)
sound_add_included("Sidewinder___Timeless___12_She_Said.ogg",1,1)
sound_add_included("Sidewinder___Timeless___17_Jasmine.ogg",1,1)
sound_add_included("Sidewinder___Timeless___19_Just_Like_That.ogg",1,1)
sound_add_included("Sidewinder___Wonderfull___01_Wonderfull.ogg",1,1)
sound_add_included("sndDeath.wav",0,1)
sound_add_included("sndDJump.wav",0,1)
sound_add_included("sndItem.wav",0,1)
sound_add_included("sndJump.wav",0,1)
sound_add_included("sndSave.wav",0,1)
sound_add_included("sndShoot.wav",0,1)
sound_add_included("thx.ogg",1,1)
sound_add_included("sndBlockBreakYuuutu.wav",0,1)
